# Generated by Django 5.2.8 on 2025-12-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('price', models.FloatField(default=0, max_length=20)),
                ('desc', models.CharField(max_length=400)),
                ('product_images', models.ImageField(upload_to='product_image/images')),
            ],
        ),
    ]
